version: '3.9'

services:

  mediscreendb:
    image: mysql
    platform: linux/amd64
    container_name: mediscreen_patient_db
    restart: always
    volumes:
      -  ./mediscreen-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=PatientsMediscreenDb
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
    - web-server

  mongodb:
      image: mongo
      container_name: mongodb
      restart: always
      ports:
        - '27017:27017'
      networks:
        - web-server


  DiabetesAssessment:
    image: diabetesassessment
    platform: linux/amd64
    container_name: mediscreendiabetesassessment
    build:
      context: MediscreenDiabetesAssessment
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mediscreenpatients
      - mediscreenhistory
    networks:
      - web-server
    restart: always

  mediscreenpatients:
    image: mediscreenpatients
    platform: linux/amd64
    container_name: mediscreenpatients
    build:
      context: MediScreenPatients
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mediscreendb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mediscreendb:3306/PatientsMediscreenDb
      SPRING_DATASOURCE_PORT: 3308
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - web-server
    restart: always

  mediscreenhistory:
    image: mediscreenhistory
    platform: linux/amd64
    container_name: mediscreenhistory
    build:
      context: MediscreenHistory/History/History
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    networks:
      - web-server
    restart: always

networks:
  web-server:
      driver: bridge